#ifndef ecManipulatorTokens_H_
#define ecManipulatorTokens_H_
//------------------------------------------------------------------------------
// Copyright (c) 2002-2013 Energid Technologies. All rights reserved.
//
/// @file ecManipulatorTokens.h
/// @brief Token definitions for the manipulator project
/// @details namespace EcManip
//
//------------------------------------------------------------------------------
#include <foundation/foundation_config.h>
#include <xml/ecToken.h>

/// Token definitions for the manipulator project
namespace EcManip
{
   ECTOKEN_DEFINITIONS(EC_FOUNDATION_MANIPULATOR_DECL,
      // Namespace for this class.  Used in later definitions.
      (ns, "http://www.energid.com/namespace/mn#")

      // Elements
      (EcAbsoluteBoundingSphereToken,                                 ns + "absoluteBoundingSphere")
      (EcAccelerationStateToken,                                      ns + "accelerationState")
      (EcActionRadiusToken,                                           ns + "actionRadius")
      (EcActiveAccelerationStateToken,                                ns + "activeAccelerationState")
      (EcActiveArticulationStateToken,                                ns + "activeArticulationState")
      (EcActiveForceStateToken,                                       ns + "activeForceState")
      (EcActiveMassStateToken,                                        ns + "activeMassState")
      (EcActivePositionStateToken,                                    ns + "activePositionState")
      (EcActiveVelocityStateToken,                                    ns + "activeVelocityState")
      (EcActuatorLastVelocitiesToken,                                 ns + "actuatorLastVelocities")
      (EcActuatorOutputTorquesToken,                                  ns + "actuatorOutputTorques")
      (EcActuatorReverseMotionPositionsToken,                         ns + "actuatorReverseMotionPositions")
      (EcActuatorSpringDamperCentersToken,                            ns + "actuatorSpringDamperCenters")
      (EcActuatorStateToken,                                          ns + "actuatorState")
      (EcActuatorStaticFrictionModesToken,                            ns + "actuatorStaticFrictionModes")
      (EcAngleRandomVariationToken,                                   ns + "angleRandomVariation")
      (EcAngularDamperConstantToken,                                  ns + "angularDamperConstant")
      (EcAngularInertiaToken,                                         ns + "angularInertia")
      (EcAngularMatrixToken,                                          ns + "angularMatrix")
      (EcAngularSpringConstantToken,                                  ns + "angularSpringConstant")
      (EcAngularSpringOffsetToken,                                    ns + "angularSpringOffset")
      (EcAngularStaticFrictionModelMaxAngularErrorToken,              ns + "angularStaticFrictionModelMaxAngularError")
      (EcArbdToken,                                                   ns + "arbd")
      (EcArbdValidToken,                                              ns + "arbdValid")
      (EcArmatureInductanceToken,                                     ns + "armatureInductance")
      (EcArmatureResistanceToken,                                     ns + "armatureResistance")
      (EcArticulatedBodyDynamicsToken,                                ns + "articulatedBodyDynamics")
      (EcArticulatedBodyInertiaToken,                                 ns + "articulatedBodyInertia")
      (EcAssociatedJointsToken,                                       ns + "associatedJoints")
      (EcAssumedMassToken,                                            ns + "assumedMass")
      (EcBacklashToken,                                               ns + "backlash")
      (EcBaseAccelerationStateToken,                                  ns + "baseAccelerationState")
      (EcBaseAngleOneSigmaToken,                                      ns + "baseAngleOneSigma")
      (EcBaseAngularVelocityOneSigmaToken,                            ns + "baseAngularVelocityOneSigma")
      (EcBaseArticulationStateToken,                                  ns + "baseArticulationState")
      (EcBaseForceStateToken,                                         ns + "baseForceState")
      (EcBaseGeneralForceToken,                                       ns + "baseGeneralForce")
      (EcBaseLinearVelocityOneSigmaToken,                             ns + "baseLinearVelocityOneSigma")
      (EcBaseLinkInterfaceToken,                                      ns + "baseLinkInterface")
      (EcBaseLinkLabelToken,                                          ns + "baseLinkLabelToken")
      (EcBaseManipulatorIndexToken,                                   ns + "baseManipulatorIndexToken")
      (EcBaseMassStateToken,                                          ns + "baseMassState")
      (EcBasePositionOneSigmaToken,                                   ns + "basePositionOneSigma")
      (EcBasePositionStateToken,                                      ns + "basePositionState")
      (EcBaseVelocityStateToken,                                      ns + "baseVelocityState")
      (EcBaseWeightsToken,                                            ns + "baseWeights")
      (EcBiasToken,                                                   ns + "articulatedBodyInertia")
      (EcCheckForCollisionsToken,                                     ns + "checkForCollisions")
      (EcChildLinksToken,                                             ns + "childLinks")
      (EcChildNodesToken,                                             ns + "childNodes")
      (EcClosedDoorAngleLowerBoundToken,                              ns + "closedDoorAngleLowerBound")
      (EcClosedDoorAngleUpperBoundToken,                              ns + "closedDoorAngleUpperBound")
      (EcClosestDistanceToken,                                        ns + "closestDistance")
      (EcClosestLinkToken,                                            ns + "closestLink")
      (EcClosestManipulatorToken,                                     ns + "closestManipulator")
      (EcCollidedLinkToken,                                           ns + "collidedLink")
      (EcCollisionBvhPrecisionLevelToken,                             ns + "collisionBvhPrecisionLevel")
      (EcCollisionDetectionFidelityToken,                             ns + "collisionDetectionFidelity")
      (EcCollisionDescriptorToken,                                    ns + "collisionDescriptor")
      (EcCollisionDetectionToleranceToken,                            ns + "collisionDetectionTolerance")
      (EcCollisionForceContainerToken,                                ns + "collisionForceContainer")
      (EcCollisionOccurredToken,                                      ns + "collisionOccurred")
      (EcCollisionExclusionDataToken,                                 ns + "collisionExclusionData")
      (EcComPolygonalStoppingCriterionToken,                          ns + "polygonalStoppingCriterion")
      (EcCompositeJointActuatorToken,                                 ns + "compositeJointActuator")
      (EcComputeKineticFrictionFlagToken,                             ns + "computeKineticFrictionFlag")
      (EcComputeStaticFrictionFlagToken,                              ns + "computeStaticFrictionFlag")
      (EcComputeViscousFrictionFlagToken,                             ns + "computeViscousFrictionFlag")
      (EcContactFrameToken,                                           ns + "contactFrame")
      (EcContactPointToken,                                           ns + "contactPoint")
      (EcContactRegionToken,                                          ns + "contactRegion")
      (EcCrbiToken,                                                   ns + "crbi")
      (EcCrbiValidToken,                                              ns + "crbiValid")
      (EcCrossMatrixToken,                                            ns + "crossMatrix")
      (EcD1LengthToken,                                               ns + "d1Length")
      (EcD2LengthToken,                                               ns + "d2Length")
      (EcDamperConstantToken,                                         ns + "damperConstant")
      (EcDamperPropertiesToken,                                       ns + "damperProperties")
      (EcDcElectricMotorToken,                                        ns + "dcElectricMotor")
      (EcDefaultAngularFrictionScaleFactorToken,                      ns + "defaultAngularFrictionScaleFactor")
      (EcDefaultAngularKineticFrictionCoefficientToken,               ns + "defaultAngularKineticFrictionCoefficient")
      (EcDefaultAngularStaticFrictionCoefficientToken,                ns + "defaultAngularStaticFrictionCoefficient")
      (EcDefaultAssumedMassToken,                                     ns + "defaultAssumedMass")
      (EcDefaultDamperConstantToken,                                  ns + "defaultDamperConstant")
      (EcDefaultJointPositionOneSigmaToken,                           ns + "defaultJointPositionOneSigma")
      (EcDefaultJointVelocityOneSigmaToken,                           ns + "defaultJointVelocityOneSigma")
      (EcDefaultLinearKineticFrictionCoefficientToken,                ns + "defaultLinearKineticFrictionCoefficient")
      (EcDefaultLinearNormalStaticFrictionCoefficientToken,           ns + "defaultLinearNormalStaticFrictionCoefficient")
      (EcDefaultLinearTangentialStaticFrictionCoefficientToken,       ns + "defaultLinearTangentialStaticFrictionCoefficient")
      (EcDefaultLinkPropertyRandomVariationToken,                     ns + "defaultLinkPropertyRandomVariation")
      (EcDefaultPositionStateRandomVariationToken,                    ns + "defaultPositionStateRandomVariation")
      (EcDefaultSpringConstantToken,                                  ns + "defaultSpringConstant")
      (EcDefaultSpringExponentToken,                                  ns + "defaultSpringExponent")
      (EcDefaultVelocityStateRandomVariationToken,                    ns + "defaultVelocityStateRandomVariation")
      (EcDefaultViscousFrictionCoefficientToken,                      ns + "defaultViscousFrictionCoefficient")
      (EcDeformationStateToken,                                       ns + "deformationState")
      (EcDeformationStatusStateToken,                                 ns + "deformationStatusState")
      (EcDeformationStateVectorToken,                                 ns + "deformationStateVector")
      (EcDeformableManipulatorLinkToken,                              ns + "deformableManipulatorLink")
      (EcDeformedShapeIndexVecToken,                                  ns + "deformedShapeIndexVec")
      (EcDenavitHartenbergToken,                                      ns + "denavitHartenberg")
      (EcDescriptiveTextToken,                                        ns + "descriptiveText")
      (EcDhAlphaToken,                                                ns + "alpha")
      (EcDhAToken,                                                    ns + "a")
      (EcDhDToken,                                                    ns + "d")
      (EcDhFrameAccelerationInLocalToken,                             ns + "frameAccelerationInLocal")
      (EcDhFrameAccelerationInSystemToken,                            ns + "frameAccelerationInSystem")
      (EcDhFrameForceInLocalToken,                                    ns + "dhFrameForceInLocal")
      (EcDhFrameToken,                                                ns + "dhFrame")
      (EcDhFrameVelocityInLocalToken,                                 ns + "dhFrameVelocityInLocal")
      (EcDhFrameVelocityInSystemToken,                                ns + "dhFrameVelocityInSystem")
      (EcDhThetaToken,                                                ns + "theta")
      (EcDhTransformValidToken,                                       ns + "dhTransformValid")
      (EcDhTypeToken,                                                 ns + "dhType")
      (EcDischargeCoefficientToken,                                   ns + "dischargeCoefficient")
      (EcDisplayLinkIndicesToken,                                     ns + "displayLinkIndices")
      (EcDissipativeForceInputToken,                                  ns + "dissipativeForceInput")
      (EcDissipativeForceOutputToken,                                 ns + "dissipativeForceOutput")
      (EcDissipativeForceProcessorToken,                              ns + "dissipativeForceProcessor")
      (EcDissipativeForceProcessorContainerToken,                     ns + "dissipativeForceProcessorContainer")
      (EcDoorLinkIdToken,                                             ns + "doorLinkId")
      (EcDrainPressureToken,                                          ns + "drainPressure")
      (EcDryFrictionForceProcessorToken,                              ns + "dryFrictionForceProcessor")
      (EcEffectiveArea1Token,                                         ns + "effectiveArea1")
      (EcEffectiveArea2Token,                                         ns + "effectiveArea2")
      (EcEnvironmentToken,                                            ns + "environment")
      (EcExternalForceDescriptionToken,                               ns + "externalForceDescription")
      (EcFirstLinkLabelToken,                                         ns + "firstLinkLabel")
      (EcFirstLinkPointToken,                                         ns + "firstLinkPoint")
      (EcExternalLinkForceToken,                                      ns + "externalLinkForce")
      (EcFirstMomentToken,                                            ns + "firstMoment")
      (EcFlowAreaGradientToken,                                       ns + "flowAreaGradient")
      (EcFluidBulkModulusToken,                                       ns + "fluidBulkModulus")
      (EcFluidDensityToken,                                           ns + "fluidDensity")
      (EcFluidVolume1Token,                                           ns + "fluidVolume1")
      (EcFluidVolume2Token,                                           ns + "fluidVolume2")
      (EcForceApplicationPointToken,                                  ns + "forceApplicationPoint")
      (EcFrameToken,                                                  ns + "frame")
      (EcFrameOffsetOneToken,                                         ns + "frameOffsetOne")
      (EcFrameOffsetTwoToken,                                         ns + "frameOffsetTwo")
      (EcFrictionCoefficientLookupToolToken,                          ns + "frictionCoefficientLookupTool")
      (EcFrictionCoefficientToken,                                    ns + "frictionCoefficient")
      (EcGearRatioToken,                                              ns + "gearRatio")
      (EcGearheadManufacturerDataVectorToken,                         ns + "gearheadManufacturerDataVector")
      (EcGeneralAccelerationToken,                                    ns + "generalAcceleration")
      (EcGeneralBoundObjectVectorToken,                               ns + "generalBoundObjectVector")
      (EcGeneralBoundObjectShapeContainerToken,                       ns + "shapeContainer")
      (EcHandleLinkIdToken,                                           ns + "handleLinkId")
      (EcHitGeneralStoppingCriterionToken,                            ns + "hitGeneralStoppingCriterion")
      (EcHitJointLimitToken,                                          ns + "hitJointLimit")
      (EcHitSingularityToken,                                         ns + "hitSingularity")
      (EcHydraulicCylinderToken,                                      ns + "hydraulicCylinder")
      (EcIdentifierToken,                                             ns + "identifier")
      (EcInertiaToken,                                                ns + "inertia")
      (EcIndividualManipulatorToken,                                  ns + "individualManipulator")
      (EcIsAttachToken,                                               ns + "isAttach")
      (EcIsControllableToken,                                         ns + "isControllable")
      (EcIsDeformableToken,                                           ns + "isDeformable")
      (EcIsFixedBaseToken,                                            ns + "isFixedBase")
      (EcIsManipulatorReferencedToken,                                ns + "isManipulatorReferenced")
      (EcIsRigidToken,                                                ns + "isRigid")
      (EcIsRigidJointToken,                                           ns + "isRigidJoint")
      (EcIsShapeReferencedToken,                                      ns + "isShapeReferenced")
      (EcIsConstrainedToken,                                          ns + "isConstrained")
      (EcJointAccelerationsToken,                                     ns + "jointAccelerations")
      (EcJointActuatorToken,                                          ns + "jointActuator")
      (EcJointActuatorContainerToken,                                 ns + "jointActuatorContainer")
      (EcJointActuatorRandomVariationToken,                           ns + "jointActuatorRandomVariation")
      (EcJointFlexibilityDampingToken,                                ns + "jointFlexibilityDamping")
      (EcJointFlexibilityStiffnessToken,                              ns + "jointFlexibilityStiffness")
      (EcJointPositionOneSigmasToken,                                 ns + "jointPositionOneSigmas")
      (EcJointPositionsToken,                                         ns + "jointPositions")
      (EcJointTorquesToken,                                           ns + "jointTorques")
      (EcJointTypeToken,                                              ns + "jointType")
      (EcJointVelocityOneSigmasToken,                                 ns + "jointVelocityOneSigmas")
      (EcJointVelocitiesToken,                                        ns + "jointVelocities")
      (EcJointWeightsToken,                                           ns + "jointWeights")
      (EcKineticCoulombFrictionPercentageToken,                       ns + "kineticCoulombFrictionPercentage")
      (EcKineticFrictionMapToken,                                     ns + "kineticFrictionMap")
      (EcKineticFrictionWeightingExponentToken,                       ns + "kineticFrictionWeightingExponent")
      (EcKinematicsConversionToolToken,                               ns + "kinematicsConversionTool")
      (EcLabelAssociatedMapToken,                                     ns + "labelAssociationMap")
      (EcLabelAssociatedMapIdentifierToken,                           ns + "labelAssociationIdentifierMap")
      (EcLabelAssociatedRealMapToken,                                 ns + "labelAssociatedRealMap")
      (EcLatchedDoorLinksToken,                                       ns + "latchedDoorLinks")
      (EcLatchTypeToken,                                              ns + "latchType")
      (EcLinearInertiaToken,                                          ns + "linearInertia")
      (EcLinearStateEqualityConstraintToken,                          ns + "linearStateEqualityConstraint")
      (EcLinearStaticFrictionModelMaxDistanceErrorToken,              ns + "linearStaticFrictionModelMaxDistanceError")
      (EcLinearStaticFrictionModelNormalToTangentialSpringRatioToken, ns + "linearStaticFrictionModelNormalToTangentialSpringRatio")
      (EcLinearDamperConstantToken,                                   ns + "linearDamperConstant")
      (EcLinearMatrixToken,                                           ns + "linearMatrix")
      (EcLinearSpringConstantToken,                                   ns + "linearSpringConstant")
      (EcLinearSpringOffsetToken,                                     ns + "linearSpringOffset")
      (EcLinkAccelerationStateToken,                                  ns + "linkAccelerationState")
      (EcLinkAccelerationStatesToken,                                 ns + "accelerationStates")
      (EcLinkArticulationStatesToken,                                 ns + "linkArticulationStates")
      (EcLinkArticulationStateToken,                                  ns + "linkArticulationState")
      (EcLinkAttachmentToken,                                         ns + "linkAttachment")
      (EcLinkCollisionEventToken,                                     ns + "linkCollisionEvent")
      (EcLinkForceStatesToken,                                        ns + "linkForceStates")
      (EcLinkForceStateToken,                                         ns + "linkForceState")
      (EcLinkGeneralForcesToken,                                      ns + "linkGeneralForces")
      (EcLinkIdentifierMapToken,                                      ns + "linkIdentifierMap")
      (EcLinkIdToken,                                                 ns + "linkId")
      (EcLinkIdentifierToken,                                         ns + "linkIndentifier")
      (EcLinkIndexAtJointLimitToken,                                  ns + "linkIndexAtJointLimit")
      (EcLinkInteractionsVectorToken,                                 ns + "linkInteractionsVector")
      (EcLinkInterfaceIdentifierToken,                                ns + "linkInterfaceIdentifier")
      (EcLinkInterfaceTypeToken,                                      ns + "linkInterfaceType")
      (EcLinkInterfaceFrameToken,                                     ns + "linkInterfaceFrame")
      (EcLinkInterfaceInUseToken,                                     ns + "linkInterfaceInUseFlag")
      (EcLinkKinematicsContainerToken,                                ns + "linkKinematicsContainer")
      (EcLinkKinematicsMorphedToken,                                  ns + "linkKinematicsMorphed")
      (EcLinkKinematicsRandomVariationToken,                          ns + "linkKinematicsRandomVariation")
      (EcLinkLinkExclusionMapToken,                                   ns + "linkLinkExclusionMap")
      (EcLinkManipulatorExclusionMapToken,                            ns + "linkManipulatorExclusionMap")
      (EcLinkMapArrayToken,                                           ns + "linkMapArray")
      (EcNamedPointsToken,                                            ns + "namedPoints")
      (EcNamedFramesToken,                                            ns + "namedFrames")
   )
   // Current limitation is 256 tokens per macro call.  Split to keep happy.
   ECTOKEN_DEFINITIONS(EC_FOUNDATION_MANIPULATOR_DECL,
      (EcLinkMassStatesToken,                                         ns + "linkMassStates")
      (EcLinkMassStateToken,                                          ns + "linkMassState")
      (EcLinkOneIndexToken,                                           ns + "linkOneIndex")
      (EcLinkPointEventToken,                                         ns + "linkPointEvent")
      (EcLinkPositionStatesToken,                                     ns + "linkPositionStates")
      (EcLinkPositionStateToken,                                      ns + "linkPositionState")
      (EcLinkPropertyRandomVariationToken,                            ns + "linkPropertyRandomVariation")
      (EcLinkReferenceDescriptionToken,                               ns + "linkReferenceDescription")
      (EcLinkShapeToMorphedShapeMapToken,                             ns + "linkShapeToMorphedShapeMap")
      (EcLinkTwoIndexToken,                                           ns + "linkTwoIndex")
      (EcLinkVelocityStatesToken,                                     ns + "linkVelocityStates")
      (EcLinkVelocityStateToken,                                      ns + "linkVelocityState")
      (EcLimitingVelocityStickRegionToken,                            ns + "limitingVelocityStickRegion")
      (EcLocalDhValidToken,                                           ns + "localDhValid")
      (EcLocationInSystemValidToken,                                  ns + "locationInSystemValid")
      (EcLowerLimitToken,                                             ns + "lowerLimit")
      (EcLowerLimitConstraintToken,                                   ns + "lowerLimitConstraint")
      (EcManipulatorActiveAccelerationStateToken,                     ns + "manipulatorActiveAccelerationState")
      (EcManipulatorActiveArticulationStateToken,                     ns + "manipulatorActiveArticulationState")
      (EcManipulatorActiveForceStateToken,                            ns + "manipulatorActiveForceState")
      (EcManipulatorActiveMassStateToken,                             ns + "manipulatorActiveMassState")
      (EcManipulatorActivePositionStateToken,                         ns + "manipulatorActivePositionState")
      (EcManipulatorActiveStateToken,                                 ns + "manipulatorActiveState")
      (EcManipulatorActiveStateVectorToken,                           ns + "manipulatorActiveStateVector")
      (EcManipulatorActiveVelocityStateToken,                         ns + "manipulatorActiveVelocityState")
      (EcManipulatorAttachmentChangeToken,                            ns + "manipulatorAttachmentChange")
      (EcManipulatorAttachmentMapToken,                               ns + "manipulatorAttachmentMap")
      (EcManipulatorAttachmentNodeToken,                              ns + "manipulatorAttachmentNode")
      (EcManipulatorAttachmentNodeVectorToken,                        ns + "manipulatorAttachmentNodeVector")
      (EcManipulatorConstraintsToken,                                 ns + "manipulatorConstraints")
      (EcManipulatorConstraintToolToken,                              ns + "manipulatorConstraintTool")
      (EcManipulatorExclusionMapToken,                                ns + "manipulatorExclusionMap")
      (EcManipulatorExternalForceToken,                               ns + "manipulatorExternalForce")
      (EcManipulatorIdToken,                                          ns + "manipulatorId")
      (EcManipulatorLinkToken,                                        ns + "manipulatorLink")
      (EcManipulatorLinkIdToken,                                      ns + "manipulatorLinkId")
      (EcManipulatorOneIndexToken,                                    ns + "manipulatorOneIndex")
      (EcManipulatorPointEventToken,                                  ns + "manipulatorPointEvent")
      (EcManipulatorRandomVariationVectorToken,                       ns + "manipulatorRandomVariationVector")
      (EcManipulatorReferenceDescriptionToken,                        ns + "manipulatorReferenceDescription")
      (EcManipulatorSelfCollisionLinkMapToken,                        ns + "manipSelfCollisionLinkMap")
      (EcManipulatorSpaceOctantMapToken,                              ns + "manipulatorSpaceOctantMap")
      (EcManipulatorsToken,                                           ns + "manipulators")
      (EcManipulatorSystemConfigurationToken,                         ns + "manipulatorSystemConfiguration")
      (EcManipulatorSystemStateToken,                                 ns + "manipulatorSystemState")
      (EcManipulatorSystemToken,                                      ns + "manipulatorSystem")
      (EcManipulatorTorqueToken,                                      ns + "manipulatorTorque")
      (EcManipulatorTwoIndexToken,                                    ns + "manipulatorTwoIndex")
      (EcManufacturerToken,                                           ns + "manufacturer")
      (EcMassRandomVariationToken,                                    ns + "massRandomVariation")
      (EcMassPropertiesToken,                                         ns + "massProperties")
      (EcMassPropertiesMapToken,                                      ns + "massPropertiesMap")
      (EcMassPropertiesMorphedToken,                                  ns + "massPropertiesMorphed")
      (EcMassPropertiesInDHFrameMorphedToken,                         ns + "massPropertiesInDHFrameMorphed")
      (EcMassPropertyRandomVariationToken,                            ns + "massPropertyRandomVariation")
      (EcMassSpringCollisionForceProcessorToken,                      ns + "massSpringCollisionForceProcessor")
      (EcMassSpringDamperCollisionForceProcessorToken,                ns + "massSpringDamperCollisionForceProcessor")
      (EcMassToken,                                                   ns + "mass")
      (EcMaxEfficiencyToken,                                          ns + "maxEfficiency")
      (EcMaxFluidLengthToken,                                         ns + "maxFluidLength")
      (EcMaxGjkIterationsToken,                                       ns + "maxGjkIterations")
      (EcMaxOutputRateToken,                                          ns + "maxOutputRate")
      (EcMaxTorqueToken,                                              ns + "maxTorque")
      (EcMaxValveOpeningToken,                                        ns + "maxValveOpening")
      (EcMechanicalActuatorComponentToken,                            ns + "ecMechanicalActuatorComponent")
      (EcMechanicalActuatorComponentContainerToken,                   ns + "ecMechanicalActuatorComponentContainer")
      (EcMinTorqueToken,                                              ns + "minTorque")
      (EcMomentXToken,                                                ns + "momentX")
      (EcMomentYToken,                                                ns + "momentY")
      (EcMomentZToken,                                                ns + "momentZ")
      (EcMorphedShapeVectorToken,                                     ns + "morphedShapeVector")
      (EcMotorAccelerationsToken,                                     ns + "motorAccelerations")
      (EcMotorPositionsToken,                                         ns + "motorPositions")
      (EcMotorVelocitiesToken,                                        ns + "motorVelocities")
      (EcMultivariableConstraintContainerToken,                       ns + "multivariableConstraintToken")
      (EcMultivariableJointStateConstraintToken,                      ns + "multivariableJointStateConstraint")
      (EcNoLoadCurrentToken,                                          ns + "noLoadCurrent")
      (EcNoLoadSpeedToken,                                            ns + "noLoadSpeed")
      (EcNominalSliderLengthToken,                                    ns + "nominalSliderLength")
      (EcNonRigidActuatorFlagsToken,                                  ns + "nonRigidActuatorFlags")
      (EcNormalStaticFrictionMapToken,                                ns + "normalStaticFrictionMap")
      (EcOffsetToken,                                                 ns + "offset")
      (EcOptimizeOnLoadToken,                                         ns + "optimizeOnLoad")
      (EcOppositeLengthToken,                                         ns + "oppositeLength")
      (EcOtherClosestLinkToken,                                       ns + "otherCollidedLink")
      (EcOtherClosestManipulatorToken,                                ns + "otherCollidedManipulator")
      (EcOtherCollidedLinkToken,                                      ns + "otherCollidedLink")
      (EcOtherCollidedManipulatorToken,                               ns + "otherCollidedManipulator")
      (EcParentLinkIdentifierToken,                                   ns + "parentLinkIdentifier")
      (EcPartNumberToken,                                             ns + "partNumber")
      (EcPassThroughPowerConverterToken,                              ns + "passThroughPowerConverter")
      (EcPitchToken,                                                  ns + "pitch")
      (EcpLinkToken,                                                  ns + "pLink")
      (EcPointCollisionEventToken,                                    ns + "pointCollisionEvent")
      (EcPointStateEqualityConstraintToken,                           ns + "pointStateEqualityConstraint")
      (EcPolygonVerticesToken,                                        ns + "polygonVertices")
      (EcPositionRandomVariationToken,                                ns + "positionRandomVariation")
      (EcPositionStatesToken,                                         ns + "positionStates")
      (EcPositionStateToken,                                          ns + "positionState")
      (EcPositionStateRandomVariationToken,                           ns + "positionStateRandomVariation")
      (EcPositionStateRandomVariationsToken,                          ns + "positionStateRandomVariations")
      (EcPowerConverterContainerToken,                                ns + "powerConverterContainer")
      (EcPowerConverterStatesToken,                                   ns + "powerConverterStates")
      (EcPrecursorToken,                                              ns + "precursor")
      (EcPrimaryFrameAccelerationInSystemToken,                       ns + "primaryFrameAccelerationInSystem")
      (EcPrimaryFrameToken,                                           ns + "primaryFrame")
      (EcPrimaryFrameVelocityInSystemToken,                           ns + "primaryFrameVelocityInSystem")
      (EcPrimeMoverManufacturerDataToken,                             ns + "primeMoverManufacturerData")
      (EcProcessingParametersToken,                                   ns + "processingParameters")
      (EcPropagationDescriptorToken,                                  ns + "propagationDescriptor")
      (EcPropagationResultDataToken,                                  ns + "propagationResultData")
      (EcQuadrilateralTypeLinkToken,                                  ns + "quadrilateralTypeLink")
      (EcQuadrilateralFixedSliderJointCBObjectToken,                  ns + "quadrilateralFixedSliderJointCBObject")
      (EcQuadrilateralFixedSliderJointOAObjectToken,                  ns + "quadrilateralFixedSliderJointOAObject")
      (EcQuadrilateralPivotedSliderJointBObjectToken,                 ns + "quadrilateralPivotedSliderJointBObject")
      (EcQuadrilateralPivotedSliderJointCObjectToken,                 ns + "quadrilateralPivotedSliderJointCObject")
      (EcReferencedLinkLabelToken,                                    ns + "referencedLinkLabel")
      (EcReferenceLinkLabelToken,                                     ns + "referenceLinkLabel")
      (EcReferencedManipulatorLabelToken,                             ns + "referencedManipulatorLabel")
      (EcRestitutionModelCollisionForceProcessorToken,                ns + "restitutionCollisionForceModelProcessor")
      (EcRigidBodyMassPropertiesToken,                                ns + "rigidBodyMassProperties")
      (EcRotationalFrictionScaleFactorToken,                          ns + "rotationalFrictionScaleFactorMap")
      (EcSatisfiedGeneralStoppingCriteriaDescriptionToken,            ns + "satisfiedGeneralStoppingCriteriaDescription")
      (EcScrewTypeLinkToken,                                          ns + "screwTypeLink")
      (EcSecondLinkLabelToken,                                        ns + "secondLinkLabel")
      (EcSecondLinkPointToken,                                        ns + "secondLinkPoint")
      (EcSelfCollisionToken,                                          ns + "selfCollision")
      (EcShapeIdToken,                                                ns + "shapeId")
      (EcShapeMorphedVectorToken,                                     ns + "shapeMorphedVector")
      (EcSpringAndDamperBetweenLinksToken,                            ns + "springAndDamperBetweenLinks")
      (EcSpringConstantToken,                                         ns + "springConstant")
      (EcSpringOffsetsToken,                                          ns + "springOffsets")
      (EcSpringPropertiesToken,                                       ns + "springProperties")
      (EcStallTorqueToken,                                            ns + "stallTorque")
      (EcStatedSystemToken,                                           ns + "statedSystem")
      (EcStateToken,                                                  ns + "state")
      (EcStateConstraintContainerToken,                               ns + "stateConstraintContainer")
      (EcStateConstraintVectorToken,                                  ns + "stateConstraintVector")
      (EcStateEqualityConstraintVectorToken,                          ns + "stateEqualityConstraintVector")
      (EcStateRandomVariationToken,                                   ns + "stateRandomVariationToken")
      (EcStaticCoulombFrictionToken,                                  ns + "staticCoulombFriction")
      (EcStaticCoulombSpringCoefficientToken,                         ns + "staticCoulombSpringCoefficient")
      (EcStaticCoulombDamperCoefficientToken,                         ns + "staticCoulombDamperCoefficient")
      (EcStaticFrictionMaxSpringForceFractionToken,                   ns + "staticFrictionMaxSpringForceFraction")
      (EcStopperDampingCoefficientToken,                              ns + "stopperDampingCoefficient")
      (EcStopperSpringCoefficientToken,                               ns + "stopperSpringCoefficient")
      (EcStopperZoneToken,                                            ns + "stopperZone")
      (EcStoppingCriteriaToken,                                       ns + "stoppingCriteria")
      (EcStoppingCriterionVectorToken,                                ns + "stoppingCriterionVector")
      (EcSupplementalDhAccelerationToken,                             ns + "supplementalDhAcceleration")
      (EcSupplementalDhAccelerationValidToken,                        ns + "supplementalDhAccelerationValid")
      (EcSupplementalJointAccelerationToken,                          ns + "supplementalJointAcceleration")
      (EcSupplementalJointAccelerationValidToken,                     ns + "supplementalJointAccelerationValid")
      (EcSupplyPressureToken,                                         ns + "supplyPressure")
      (EcSurfaceMaterialToken,                                        ns + "surfaceMaterial")
      (EcSurfacePropertyToken,                                        ns + "surfaceProperty")
      (EcSurfacePropertyMapToken,                                     ns + "surfacePropertyMap")
      (EcSurfacePropertyRandomVariationToken,                         ns + "surfacePropertyRandomVariation")
      (EcSurfacePropertyRandomVariationVectorToken,                   ns + "surfacePropertyRandomVariationVector")
      (EcSystemActiveBoundingBoxStateToken,                           ns + "systemActiveBoundingBoxState")
      (EcSystemActiveStateToken,                                      ns + "systemActiveState")
      (EcSystemCollisionExclusionMapToken,                            ns + "systemCollisionExclusionSet")
      (EcSystemDhValidToken,                                          ns + "systemDhValid")
      (EcSystemPointEventToken,                                       ns + "systemPointEvent")
      (EcSystemPrimaryValidToken,                                     ns + "systemPrimaryValid")
      (EcSystemProcessingParametersToken,                             ns + "systemProcessingParameters")
      (EcSystemRandomVariationToken,                                  ns + "systemRandomVariation")
      (EcSystemToken,                                                 ns + "system")
      (EcSystemCollisionMapToken,                                     ns + "systemCollisionMap")
      (EcTensionDamperConstantRandomVariationToken,                   ns + "tensionDamperConstantRandomVariation")
      (EcTensionSpringConstantRandomVariationToken,                   ns + "tensionSpringConstantRandomVariation")
      (EcTangentialStaticFrictionMapToken,                            ns + "tangentialStaticFrictionMap")
      (EcTimeToken,                                                   ns + "time")
      (EcTorqueConstantToken,                                         ns + "torqueConstant")
      (EcTorqueRandomVariationToken,                                  ns + "torqueRandomVariation")
      (EcTorsionalRepulsionContributionFactorToken,                   ns + "torsionalRepulsionContributionFactor")
      (EcTranslationRandomVariationToken,                             ns + "translationRandomVariation")
      (EcUnlatchingAngleLowerBoundToken,                              ns + "unlatchingAngleLowerBound")
      (EcUnlatchingAngleUpperBoundToken,                              ns + "unlatchingAngleUpperBound")
      (EcUpGravityVectorToken,                                        ns + "upGravityVector")
      (EcUpperLimitToken,                                             ns + "upperLimit")
      (EcUpperLimitConstraintToken,                                   ns + "upperLimitConstraint")
      (EcUseFrictionToken,                                            ns + "useFriction")
      (EcVelocityRandomVariationToken,                                ns + "velocityRandomVariation")
      (EcVelocityStatesToken,                                         ns + "velocityStates")
      (EcVelocityStateToken,                                          ns + "velocityState")
      (EcVelocityStateRandomVariationToken,                           ns + "velocityStateRandomVariation")
      (EcVelocityStateRandomVariationsToken,                          ns + "velocityStateRandomVariations")
      (EcViscousFrictionMapToken,                                     ns + "viscousFrictionMap")
      (EcWeightedSumsToken,                                           ns + "weightedSums")
      (EcWeightingFactorsToken,                                       ns + "weightingFactors")
      (EcWeightsToken,                                                ns + "weights")
      (EcXyOrientationToken,                                          ns + "xyOrientation")
      (EcXyStateEqualityConstraintToken,                              ns + "xyStateEqualityConstraint")
      (EcZDistanceAToken,                                             ns + "zDistanceA")
      (EcZDistanceBToken,                                             ns + "zDistanceB")
      (EcZDistanceCToken,                                             ns + "zDistanceC")

      // Enumerations ... don't need namespace
      (EcDhTypeCraigToken,                                            "craig")
      (EcDhTypeGeneralToken,                                          "general")
      (EcDhTypeGeneralCraigToken,                                     "generalCraig")
      (EcDhTypeGeneralPaulToken,                                      "generalPaul")
      (EcDhTypePaulToken,                                             "paul")
      (EcFixedSliderJointToken,                                       "fixedSliderJoint")
      (EcJointTypePrismaticToken,                                     "prismatic")
      (EcJointTypeRotationalToken,                                    "rotational")
      (EcLatchTypeClosedWithTurnToken,                                "closedWithTurn")
      (EcLatchTypeClosedWithoutTurnToken,                             "closedWithoutTurn")
      (EcModeArbitraryToken,                                          "arbitrary")
      (EcModeNoChangeToken,                                           "noChange")
      (EcModeNoRotationToken,                                         "noRotation")
      (EcModeNoTranslationToken,                                      "noTranslation")
      (EcPivotedSliderJointToken,                                     "pivotedSliderJoint")
      (EcSurfaceTensionSpringExponentToken,                           "ecSurfaceTensionSpringExponent")
      (EcSurfaceTensionDamperConstantToken,                           "ecSurfaceTensionDamperConstant")
      (EcSurfaceTensionTorsionalSpringConstantToken,                  "ecSurfaceTensionTorsionalSpringConstant")
      (EcSurfaceTensionTorsionalDamperConstantToken,                  "ecSurfaceTensionTorsionalDamperConstant")
      (EcTotalReadableLinkCountToken,                                 "totalReadableLinkCount")
      (EcCollisionAvoidanceMetricToken,                               "ecCollisionAvoidanceMetric")
   )
}

#endif // ecManipulatorTokens_H_
