#ifndef ecSimulationTokens_H_
#define ecSimulationTokens_H_
//------------------------------------------------------------------------------
// Copyright (c) 2002-2013 Energid Technologies. All rights reserved.
//
/// @file ecSimulationTokens.h
/// @brief Holds simulation tokens.
/// @details namespace EcSim
//
//------------------------------------------------------------------------------
#include <actin/actin_config.h>
#include <xml/ecToken.h>

/// Holds simulation tokens.
namespace EcSim
{
   ECTOKEN_DEFINITIONS(EC_ACTIN_SIMULATION_DECL,
      // Namespace for this class.  Used in later definitions.
      (ns, "http://www.energid.com/namespace/sm#")

      // Elements
      (EcAccumulateDeformationToken,                          ns + "accumulateDeformation")
      (EcActivateTextureMarkingToken,                         ns + "activateTextureMarking")
      (EcActuatorDynamicSimulatorToken,                       ns + "actuatorDynamicSimulator")
      (EcActuatorIntegratorToken,                             ns + "actuatorIntegrator")
      (EcActuatorMotionIntegratorToken,                       ns + "actuatorMotionIntegrator")
      (EcAdamsBashforthMoultonToken,                          ns + "adamsBashforthMoulton")
      (EcAssumedInertiaToken,                                 ns + "assumedInertia")
      (EcCenterOfInterestToken,                               ns + "centerOfInterest")
      (EcCollisionForceProcessorVectorToken,                  ns + "collisionForceProcessorVector")
      (EcConstantValueToken,                                  ns + "constantValue")
      (EcConstantIndividualJointControllerToken,              ns + "constantIndividualJointController")
      (EcControlInputConverterContainerToken,                 ns + "controlInputConverterContainer")
      (EcControlPtsIdOnRVTToken,                              ns + "controlPtsIdOnRVT")
      (EcControlStatedSystemToken,                            ns + "controlStatedSystem")
      (EcCuttingProcessorToken,                               ns + "cuttingProcessor")
      (EcDampingRatioToken,                                   ns + "dampingRatio")
      (EcDataPlotParametersToken,                             ns + "dataPlotParameters")
      (EcDefaultCutOpeningDistanceToken,                      ns + "defaultCutOpeningDistance")
      (EcDefaultJointControllerToken,                         ns + "defaultJointController")
      (EcDefaultPoissonToken,                                 ns + "defaultPoisson")
      (EcDefaultProcessorIndexToken,                          ns + "defaultProcessorIndex")
      (EcDefaultRadiusOfInfluenceToken,                       ns + "defaultRadiusOfInfluence")
      (EcDefaultYoungsModulusToken,                           ns + "defaultYoungsModulus")
      (EcDeformationProcessorContainerToken,                  ns + "deformationProcessorContainer")
      (EcDeformationProcessorInputToken,                      ns + "deformationProcessorInput")
      (EcDirectControlToken,                                  ns + "directControl")
      (EcDisplaySystemDataCaptureToken,                       ns + "displaySystemDataCapture")
      (EcDynamicallySimulateToken,                            ns + "dynamicallySimulate")
      (EcDynamicSimulatorsToken,                              ns + "dynamicSimulators")
      (EcDynamicSimulatorSystemTimeStepToken,                 ns + "dynamicSimSystemTimeStep")
      (EcDynamicSimulatorSystemToken,                         ns + "dynamicSimulatorSystem")
      (EcDynamicSimulatorToken,                               ns + "dynamicSimulator")
      (EcEndEffectorToken,                                    ns + "endEffector")
      (EcEndPointIdToken,                                     ns + "endPointId")
      (EcExplicitPositionGainToken,                           ns + "explicitPositionGain")
      (EcExplicitVelocityGainToken,                           ns + "explicitVelocityGain")
      (EcExclusivePluginLoadToken,                            ns + "exclusivePluginLoading")
      (EcEyepointToken,                                       ns + "eyepoint")
      (EcFeedforwardManipulatorJointControllerToken,          ns + "feedforwardManipulatorJointController")
      (EcFeedforwardKinLoopsManipulatorJointControllerToken,  ns + "feedforwardKinLoopsManipulatorJointController")
      (EcForceControlSystemToken,                             ns + "forceControlSystem")
      (EcFrameRateToken,                                      ns + "frameRate")
      (EcGeneralControlInputToken,                            ns + "generalControlInput")
      (EcGeneralMotionToken,                                  ns + "generalMotion")
      (EcImageSensorVectorToken,                              ns + "imageSensorVector")
      (EcIndividualDynamicSimulatorToken,                     ns + "individualDynamicSimulator")
      (EcIndividualJointControllerToken,                      ns + "individualJointController")
      (EcIndividualJointControllerContainerToken,             ns + "individualJointControllerContainer")
      (EcInitialControlModeToken,                             ns + "initialControlMode")
      (EcInitiallyControlledManipulatorToken,                 ns + "initiallyControlledManipulator")
      (EcInitialTimeScaleToken,                               ns + "initialTimeScale")
      (EcInsertionProcessorToken,                             ns + "insertionProcessor")
      (EcIntegrationMethodToken,                              ns + "integrationMethod")
      (EcIntegrationOrderToken,                               ns + "integrationOrder")
      (EcIntegrationTypeToken,                                ns + "integrationType")
      (EcIntegratorContainerToken,                            ns + "integratorContainer")
      (EcIsForceControlOnToken,                               ns + "isForceControlOn")
      (EcIsOnToken,                                           ns + "isOn")
      (EcJointControllerCollectionToken,                      ns + "jointControllerCollection")
      (EcJointControllerSystemToken,                          ns + "jointControllerSystem")
      (EcJointControllerSystemContainerToken,                 ns + "jointControllerSystemContainer")
      (EcJointControlInputsToken,                             ns + "jointControlInputs")
      (EcJointPositionOneSigmasToken,                         ns + "jointPositionOneSigmas")
      (EcJointTorqueOneSigmasToken,                           ns + "jointTorqueOneSigmas")
      (EcJointVelocityOneSigmasToken,                         ns + "jointVelocityOneSigmas")
      (EcManipulatorBaseIntegratorToken,                      ns + "manipulatorBaseIntegrator")
      (EcManipulatorControlInputToken,                        ns + "manipulatorControlInput")
      (EcManipulatorGraspingModules,                          ns + "manipulatorGraspingModules")
      (EcManipulatorJointControllerToken,                     ns + "manipulatorJointController")
      (EcManipulatorJointControllersToken,                    ns + "manipulatorJointControllers")
      (EcManipulatorJointControllerVectorToken,               ns + "manipulatorJointControllerVector")
      (EcManipulatorJointIntegratorToken,                     ns + "manipulatorJointIntegrator")
      (EcMarkerColorToken,                                    ns + "markerColor")
      (EcMarkerThicknessToken,                                ns + "markerThickness")
      (EcMaxIterationsToken,                                  ns + "maxIterations")
      (EcMaxOutputToken,                                      ns + "maxOutput")
      (EcMaxTimeScaleToken,                                   ns + "maxTimeScale")
      (EcMethodOfFiniteSphereProcessorToken,                  ns + "methodOfFiniteSphereProcessor")
      (EcMinOutputToken,                                      ns + "minOutput")
      (EcMultiCollisionForceProcessorToken,                   ns + "multiCollisionForceProcessor")
      (EcNoiseFlagToken,                                      ns + "noiseFlag")
      (EcOutputDirectoryToken,                                ns + "outputDirectory")
      (EcOutputFileNameToken,                                 ns + "outputFileName")
      (EcOutputWriterVectorToken,                             ns + "outputWriterVector")
      (EcPerformDeformationProcessingToken,                   ns + "performDeformationProcessing")
      (EcPlotAreaHeightToken,                                 ns + "plotAreaHeight")
      (EcPlotAreaWidthToken,                                  ns + "plotAreaWidth")
      (EcPluginLoadPairToken,                                 ns + "pluginConfigVector")
      (EcPointAToken,                                         ns + "pointA")
      (EcPointBToken,                                         ns + "pointB")
      (EcPointIndexAToken,                                    ns + "pointIndexA")
      (EcPointIndexBToken,                                    ns + "pointIndexB")
      (EcPowerConverterIntegratorToken,                       ns + "powerConverterIntegrator")
      (m_PrevPointAToken,                                     ns + "prevPointA")
      (m_PrevPointBToken,                                     ns + "prevPointB")
      (EcProcessorMapToken,                                   ns + "processorMap")
      (EcProxyJointsToken,                                    ns + "proxyJoints")
      (EcRadiusOfInfluenceDeformationProcessorToken,          ns + "radiusOfInfluenceDeformationProcessor")
      (EcRenderableBvLevelToken,                              ns + "renderableBvLevel")
      (EcRunOnLoadToken,                                      ns + "runOnLoad")
      (EcRandomNumberSeedToken,                               ns + "randomNumberSeed")
      (EcRegionsOfVisibleTwitchProcessorToken,                ns + "regionsOfVisibleTwitchProcessor")
      (EcResetDeformationToken,                               ns + "resetDeformation")
      (EcShapeKeyAToken,                                      ns + "shapeKeyA")
      (EcShapeKeyBToken,                                      ns + "shapeKeyB")
      (EcShareStatedSystemWithControlToken,                   ns + "shareStatedSystemWithControl")
      (EcSimulationAndStudyToken,                             ns + "simulationAndStudy")
      (EcSimulationPositionControlContainerToken,             ns + "positionControlContainer")
      (EcSimulationToken,                                     ns + "simulation")
      (EcSimulationTypeToken,                                 ns + "simulationType")
      (EcSizeOfRegionToken,                                   ns + "sizeOfRegion")
      (EcStatedSystemToken,                                   ns + "statedSystem")
      (EcStateRandomVariationToken,                           ns + "stateRandomVariation")
      (EcStateVariableBoundToken,                             ns + "stateVariableBound")
      (EcStorageSystemDataCaptureToken,                       ns + "storageSystemDataCapture")
      (EcSystemControlExecutiveToken,                         ns + "systemControlExecutive")
      (EcSystemRandomVariationToken,                          ns + "systemRandomVariation")
      (EcTimeBetweenMassMatrixEvaluationsToken,               ns + "timeBetweenMassMatrixEvaluations")
      (EcTimeScaleFactorToken,                                ns + "timeScaleFactor")
      (EcTimeStepToken,                                       ns + "timeStep")
      (EcLimitingGrowthFactorToken,                           ns + "limitingGrowthFactor")
      (EcTipPointIdToken,                                     ns + "tipPointId")
      (EcTransBToAToken,                                      ns + "transAToB")
      (EcTwitchDeltaAmplitudeToken,                           ns + "twitchDeltaAmplitude")
      (EcTwitchFrequencyToken,                                ns + "twitchFrequency")
      (EcTwitchMaxAmplitudeToken,                             ns + "twitchMaxAmplitude")
      (EcUndampedFrequencyToken,                              ns + "undampedFrequency")
      (EcUseControlTorquesInDynamicSimulationToken,           ns + "useControlTorquesInDynamicSimulation")
      (EcUseExplicitGainsIgnoreDampingRatioAndFrequencyToken, ns + "useExplicitGainsIgnoreDampingRatioAndFrequency")
      (EcVariableManipulatorJointControllersToken,            ns + "variableManipulatorJointControllers")
      (EcViewerParametersToken,                               ns + "viewerParameters")
      (EcVisualizationParametersToken,                        ns + "visualizationParameters")
      (EcZmpPlaneToken,                                       ns + "zmpPlane")

      // Enumerations ... don't need namespace
      (EcArbiToken,                                           "arbi")
      (EcAutomaticToken,                                      "automatic")
      (EcCrbiPaulToken,                                       "crbiPaul")
      (EcCrbiToken,                                           "crbi")
      (EcFirstDerivativesOnlyToken,                           "firstDerivativesOnly")
      (EcFirstAndSecondDerivativesToken,                      "firstAndSecondDerivatives")
   )
}

#endif // ecSimulationTokens_H_
