#ifndef ecManipulationTokens_H_
#define ecManipulationTokens_H_
//------------------------------------------------------------------------------
// Copyright (c) 2004-2013 Energid Technologies. All rights reserved.
//
/// @file ecManipulationTokens.h
/// @brief Tokens for manipulation project
/// @details namespace EcManipulation
//
//------------------------------------------------------------------------------
#include <actin/actin_config.h>
#include <xml/ecToken.h>

/// Tokens for manipulation project
namespace EcManipulation
{
   ECTOKEN_DEFINITIONS(EC_ACTIN_MANIPULATION_DECL,
      // Namespace for this class.  Used in later definitions.
      (ns, "http://www.energid.com/namespace/ct#")

      // Elements
      (EcAbsoluteAngleFlagToken,                                 ns + "absoluteAngleFlag")
      (EcActionMapToken,                                         ns + "actionMap")
      (EcActualOffsetToken,                                      ns + "actualOffset")
      (EcActionOrderToken,                                       ns + "actionOrder")
      (EcActualPlacementManipulationOffsetToken,                 ns + "actualPlacementManipulationOffset")
      (EcActualPlacementManipulationOffsetStateToken,            ns + "actualPlacementManipulationOffsetState")
      (EcAngleValuesToken,                                       ns + "angleValues")
      (EcAngularZoneToken,                                       ns + "angularZone")
      (EcAverageDistanceDataToken,                               ns + "averageDistanceData")
      (EcBezierInterpolatorToken,                                ns + "bezierInterpolator")
      (EcBisectionManipulationContactLocatorToken,               ns + "bisectionManipulationContactLocator")
      (EcBreakPointToken,                                        ns + "breakPoint")
      (EcBreakPointTesterToken,                                  ns + "breakPointTester")
      (EcCameraControlActionToken,                               ns + "cameraControlAction")
      (EcCaptureImageToken,                                      ns + "captureImage")
      (EcComparisonShapeFeatureHistogramToken,                   ns + "comparisonShapeFeatureHistogram")
      (EcConstantManipulationOffsetToken,                        ns + "constantManipulationOffset")
      (EcConstantManipulationOffsetStateToken,                   ns + "constantManipulationOffsetState")
      (EcConvergenceValueToken,                                  ns + "convergenceValue")
      (EcConvergenceWindowToken,                                 ns + "convergenceWindow")
      (EcConvergenceWindowStartTimeToken,                        ns + "convergenceWindowStartTime")
      (EcCurrentFrameIndexToken,                                 ns + "currentFrameIndex")
      (EcCurrentFrameIsCompleteToken,                            ns + "currentFrameIsComplete")
      (EcCurrentFrameNeedsInitToken,                             ns + "currentFrameNeedsInit")
      (EcCurrentSequenceIndexToken,                              ns + "currentSequenceIndex")
      (EcCurrentSequenceIsCompleteToken,                         ns + "currentSequenceIsComplete")
      (EcCurrentSequenceNeedsInitToken,                          ns + "currentSequenceNeedsInit")
      (EcCurrentSequenceStateContainerToken,                     ns + "currentSequenceStateContainer")
      (EcCurrentWaypointIndexToken,                              ns + "currentWaypointIndex")
      (EcCurrentWaypointIsCompleteToken,                         ns + "currentWaypointIsComplete")
      (EcCurrentWaypointNeedsInitToken,                          ns + "currentWaypointNeedsInit")
      (EcDesiredPlacementToken,                                  ns + "desiredPlacement")
      (EcEndEffectorAccelerationToken,                           ns + "endEffectorAcceleration")
      (EcEndEffectorDecelerationToken,                           ns + "endEffectorDeceleration")
      (EcEndEffectorIndexToken,                                  ns + "endEffectorIndex")
      (EcEndEffectorSpeedToken,                                  ns + "endEffectorSpeed")
      (EcExtendedZoneRadiusToken,                                ns + "extendedZoneRadius")
      (EcFocusDistanceToken,                                     ns + "focusDistance")
      (EcFrameIndexToken,                                        ns + "frameIndex")
      (EcFrameRelativeManipulationOffsetToken,                   ns + "frameRelativeManipulationOffset")
      (EcFrameRelativeManipulationOffsetStateToken,              ns + "frameRelativeManipulationOffsetState")
      (EcGripperActionToken,                                     ns + "gripperAction")
      (EcGripperClosedPositionToken,                             ns + "gripperClosedPosition")
      (EcGripperDesiredPositionPercentageToken,                  ns + "gripperDesiredPositionPercentage")
      (EcGripperOpenPositionToken,                               ns + "gripperOpenPosition")
      (EcIndexToken,                                             ns + "index")
      (EcInitialConvergenceValueToken,                           ns + "initialConvergenceValue")
      (EcInitialConvergenceValueIsSetToken,                      ns + "initialConvergenceValueIsSet")
      (EcInitializationTimeToken,                                ns + "initializationTime")
      (EcInterpolateToken,                                       ns + "interpolate")
      (EcInterpolatedCurrentOffsetToken,                         ns + "interpolatedCurrentOffset")
      (EcInterpolatedInitialOffsetToken,                         ns + "interpolatedInitialOffset")
      (EcInterpolatedManipulationOffsetToken,                    ns + "interpolatedManipulationOffset")
      (EcInterpolatedManipulationOffsetStateToken,               ns + "interpolatedManipulationOffsetState")
      (EcInterpolationTimeToken,                                 ns + "interpolationTime")
      (EcIsNormalizedToken,                                      ns + "isNormalized")
      (EcIsRelativeToken,                                        ns + "isRelative")
      (EcJointFrameToken,                                        ns + "jointFrame")
      (EcJointFrameSequenceToken,                                ns + "jointFrameSequence")
      (EcJointFrameVectorToken,                                  ns + "jointFrameVector")
      (EcJointPositionRangesToken,                               ns + "jointPositionRanges")
      (EcKeyActionToken,                                         ns + "keyAction")
      (EcKeyNameToken,                                           ns + "keyName")
      (EcLinkFrameTypeToken,                                     ns + "linkFrameType")
      (EcLinkIdentifiersToken,                                   ns + "linkIdentifiers")
      (EcLinkInterfaceConnectionPropertiesToken,                 ns + "linkInterfaceConnectionProperties")
      (EcLinkLabelsToken,                                        ns + "linkLabels")
      (EcLinkRelativeManipulationOffsetToken,                    ns + "linkRelativeManipulationOffset")
      (EcLinkRelativeManipulationOffsetStateToken,               ns + "linkRelativeManipulationOffsetState")
      (EcManipulationActionContainerToken,                       ns + "manipulationActionContainer")
      (EcManipulationActionDirectoryToken,                       ns + "manipulationActionDirectory")
      (EcManipulationActionManagerToken,                         ns + "manipulationActionManager")
      (EcManipulationActionStateContainerToken,                  ns + "manipulationActionStateContainer")
      (EcManipulationActiveControlDescriptionToken,              ns + "manipulationActiveControlDescription")
      (EcManipulationActiveForceControlDescriptionToken,         ns + "manipulationActiveForceControlDescription")
      (EcManipulationCurrentEndEffectorPlacementToken,           ns + "manipulationCurrentEndEffectorPlacement")
      (EcManipulationForceToken,                                 ns + "manipulationForce")
      (EcManipulationFrameContainerToken,                        ns + "manipulationFrameContainer")
      (EcManipulationFrameContainerVectorToken,                  ns + "manipulationFrameVector")
      (EcManipulationFrameStateContainerToken,                   ns + "manipulationFrameStateContainer")
      (EcManipulationFrameStateContainerVectorToken,             ns + "manipulationFrameStateVector")
      (EcManipulationFrameTransitionEventToken,                  ns + "manipulationFrameTransitionEvent")
      (EcManipulationFrameTransitionEventContainerToken,         ns + "manipulationFrameTransitionEventContainer")
      (EcManipulationFrameTransitionEventStateToken,             ns + "manipulationFrameTransitionEventState")
      (EcManipulationFrameTransitionEventStateContainerToken,    ns + "manipulationFrameTransitionEventStateContainer")
      (EcManipulationFrameXAxisSourceFrame,                      ns + "manipulationFrameXAxisSourceFrame")
      (EcManipulationFrameXAxisVector,                           ns + "manipulationFrameXAxisVector")
      (EcManipulationFrameYAxisSourceFrame,                      ns + "manipulationFrameYAxisSourceFrame")
      (EcManipulationFrameYAxisVector,                           ns + "manipulationFrameYAxisVector")
      (EcManipulationFrameZAxisSourceFrame,                      ns + "manipulationFrameZAxisSourceFrame")
      (EcManipulationFrameZAxisVector,                           ns + "manipulationFrameZAxisVector")
      (EcManipulationGoalEndEffectorPlacementToken,              ns + "manipulationGoalEndEffectorPlacement")
      (EcManipulationOffsetToken,                                ns + "manipulationOffset")
      (EcManipulationOffsetContainerToken,                       ns + "manipulationOffsetContainer")
      (EcManipulationOffsetContainerVectorToken,                 ns + "manipulationOffsetContainerVector")
      (EcManipulationOffsetStateToken,                           ns + "manipulationOffsetState")
      (EcManipulationOffsetStateContainerToken,                  ns + "manipulationOffsetStateContainer")
      (EcManipulationOffsetStateContainerVectorToken,            ns + "manipulationOffsetStateContainerVector")
      (EcManipulationPlacementAchievedTransitionEventToken,      ns + "placementAchievedTransitionEvent")
      (EcManipulationPlacementAchievedTransitionEventStateToken, ns + "placementAchievedTransitionEventState")
      (EcManipulationSequenceToken,                              ns + "manipulationSequence")
      (EcManipulationSequenceStateToken,                         ns + "manipulationSequenceState")
      (EcManipulationSequenceManagerToken,                       ns + "manipulationSequenceManager")
      (EcManipulationSequenceManagerStateToken,                  ns + "manipulationSequenceManagerState")
      (EcManipulationSequenceMapToken,                           ns + "manipulationSequenceMap")
      (EcManipulationTimeDurationTransitionEventToken,           ns + "timeDurationTransitionEvent")
      (EcManipulationTimeDurationTransitionEventStateToken,      ns + "timeDurationTransitionEventState")
      (EcManipulationWaypointToken,                              ns + "manipulationWaypoint")
      (EcManipulationWaypointVectorToken,                        ns + "manipulationWaypointVector")
      (EcMultiArmWaypointSequenceToken,                          ns + "multiArmWaypointSequence")
      (EcMultiArmWaypointSequenceStateToken,                     ns + "multiArmWaypointSequenceState")
      (EcMaxValueToken,                                          ns + "maxValue")
      (EcNameToken,                                              ns + "name")
      (EcNamedFrameToken,                                        ns + "namedFrame")
      (EcNumAngleBinsToken,                                      ns + "numAngleBins")
      (EcNumDistanceBinsToken,                                   ns + "numDistanceBins")
      (EcNumPointsToken,                                         ns + "numPoints")
      (EcObjectRelativeManipulationOffsetToken,                  ns + "objectRelativeManipulationOffset")
      (EcObjectRelativeManipulationOffsetStateToken,             ns + "objectRelativeManipulationOffsetState")
      (EcParametricCurrentOffsetToken,                           ns + "parametricCurrentOffset")
      (EcParametricIndexToken,                                   ns + "parametricIndex")
      (EcParametricManipulationFrameToken,                       ns + "parametricManipulationFrame")
      (EcParametricManipulationFrameStateToken,                  ns + "parametricManipulationFrameState")
      (EcParametricTagToken,                                     ns + "parametricTag")
      (EcParametricTransformToken,                               ns + "parametricTransform")
      (EcParametricTranslationManipulationOffsetToken,           ns + "parametricTranslationManipulationOffset")
      (EcParametricTranslationManipulationOffsetStateToken,      ns + "parametricTranslationManipulationOffsetState")
      (EcParametricValuesToken,                                  ns + "parametricValues")
      (EcParametricXTagToken,                                    ns + "parametricXTag")
      (EcParametricYTagToken,                                    ns + "parametricYTag")
      (EcParametricZTagToken,                                    ns + "parametricZTag")
      (EcPathActionToken,                                        ns + "pathAction")
      (EcPathPlaybackModeToken,                                  ns + "pathPlaybackMode")
      (EcPlacementConvergenceValueToken,                         ns + "placementConvergenceValue")
      (EcPlacementConvergenceWindowToken,                        ns + "placementConvergenceWindow")
      (EcPlacementConvergenceWindowStartTimeToken,               ns + "placementConvergenceWindowStartTime")
      (EcPlacementTestIndicesToken,                              ns + "placementTestIndices")
      (EcPlacementToleranceToken,                                ns + "placementTolerance")
      (EcPoseToken,                                              ns + "pose")
      (EcPoseMapToken,                                           ns + "poseMap")
      (EcPoseSetToken,                                           ns + "poseSet")
      (EcProgressToken,                                          ns + "progress")
      (EcProxyActionStateToken,                                  ns + "proxyActionState")
      (EcReferencePoseManipulationOffsetToken,                   ns + "referencePoseManipulationOffset")
      (EcReferencePoseManipulationOffsetStateToken,              ns + "referencePoseManipulationOffset")
      (EcRelativeCurrentOffsetToken,                             ns + "relativeCurrentOffset")
      (EcRelativeOffsetToken,                                    ns + "relativeOffset")
      (EcRelativeOffsetStateToken,                               ns + "relativeOffsetState")
      (EcRoleNameToken,                                          ns + "roleName")
      (EcScaleToken,                                             ns + "scale")
      (EcSequenceMapToken,                                       ns + "sequenceMap")
      (EcSequenceOrderToken,                                     ns + "sequenceOrder")
      (EcSizeToken,                                              ns + "size")
      (EcSoftFailureToken,                                       ns + "softFailure")
      (EcStandardManipulationFrameToken,                         ns + "standardManipulationFrame")
      (EcStandardManipulationFrameStateToken,                    ns + "standardManipulationFrameState")
      (EcStepSizeToken,                                          ns + "stepSize")
      (EcStopPointToken,                                         ns + "stopPoint")
      (EcSubdirectoryMapToken,                                   ns + "subdirectoryMap")
      (EcSubsequenceStateContainerToken,                         ns + "subsequenceStateContainer")
      (EcSubsequenceManipulationFrameToken,                      ns + "subsequenceManipulationFrame")
      (EcSubsequenceManipulationFrameStateToken,                 ns + "subsequenceManipulationFrameState")
      (EcTagToken,                                               ns + "tag")
      (EcTargetFrameToken,                                       ns + "targetFrame")
      (EcTargetFrameStateToken,                                  ns + "targetFrameState")
      (EcTargetOffsetToken,                                      ns + "targetOffset")
      (EcTargetOffsetStateToken,                                 ns + "targetOffsetState")
      (EcTestIndicesToken,                                       ns + "testIndices")
      (EcTimeDurationToken,                                      ns + "timeDuration")
      (EcTimeoutPeriodToken,                                     ns + "timeoutPeriod")
      (EcTimeoutStartTimeToken,                                  ns + "timeoutStartTime")
      (EcToleranceToken,                                         ns + "tolerance")
      (EcTriggerTimeToken,                                       ns + "triggerTime")
      (EcUseIndexToken,                                          ns + "useIndex")
      (EcWaypointInterpolatorToken,                              ns + "waypointInterpolator")
      (EcWaypointInterpolatorContainerToken,                     ns + "waypointInterpolatorContainer")
      (EcWaypointSequenceDatabaseToken,                          ns + "waypointSequenceDatabase")
      (EcWaypointSequenceMapToken,                               ns + "waypointSequenceMap")
      (EcWaypointSequenceToken,                                  ns + "waypointSequence")
      (EcWaypointSequenceStateToken,                             ns + "waypointSequenceState")
      (EcWaypointSequenceStateVectorToken,                       ns + "waypointSequenceStateVector")
      (EcWaypointSequenceVectorToken,                            ns + "waypointSequenceVector")
      (EcZoneRadiusToken,                                        ns + "zoneRadius")

      // Enumerations ... don't need namespace
      (EcDhFrameToken,                                           "dhFrame")
      (EcEndEffectorToken,                                       "endEffector")
      (EcObjectFrameToken,                                       "objectFrame")
      (EcPrimaryFrameToken,                                      "primaryFrame")
      (EcStateToken,                                             "state")
      (EcSystemFrameToken,                                       "systemFrame")
      (EcUndefinedFrameToken,                                    "undefinedFrame")
   )
}

#endif // ecManipulationTokens_H_
