#ifndef ecBaseRigidWheelSoilInteraction_H_
#define ecBaseRigidWheelSoilInteraction_H_
//------------------------------------------------------------------------------
// Copyright (c) 2004-2013 Energid Technologies. All rights reserved.
//
/// @file ecBaseRigidWheelSoilInteraction.h
/// @class EcBaseRigidWheelSoilInteraction
/// @brief An base class for computing interaction force between
///        rigid wheel and soil
//
//------------------------------------------------------------------------------
#include <actin/actin_config.h>  // Required to be first header.
#include <xml/ecXmlCompType.h>

// forward declarations
class EcDataMap;
class EcMobilityParameters;

/// type definition of EcWheelProperties
typedef EcDataMap EcWheelProperties;
/// type definition of EcSoilProperties
typedef EcDataMap EcSoilProperties;

class EC_ACTIN_SOILMECHANICS_DECL EcBaseRigidWheelSoilInteraction : public EcXmlCompoundType
{
public:
   /// return the list of all necessary wheel properties for this wheel-soil interaction
   virtual const EcStringVector& requiredWheelProperties
      (
      ) const=0;

   /// return the list of all necessary soil properties for this wheel-soil interaction
   virtual const EcStringVector& requiredSoilProperties
      (
      ) const=0;

   /// set the wheel properties
   virtual EcBoolean setWheelProperties
      (
      const EcWheelProperties& wheelProps
      )=0;

   /// set the soil properties
   virtual EcBoolean setSoilProperties
      (
      const EcSoilProperties& soilProps
      )=0;

   /// set the parameters
   virtual void setParameters
      (
      const EcMobilityParameters& params
      )=0;

   /// compute and return the tractive force generated by the wheel
   virtual EcReal tractiveForce
      (
      ) const=0;

   /// compute and return the motion resistive force along the wheel
   virtual EcReal resistiveForce
      (
      ) const=0;

   /// compute and return the lateral force perpendicular to the wheel
   virtual EcReal lateralForce
      (
      ) const=0;

   /// compute and return the vertical force on the wheel
   virtual EcReal verticalForce
      (
      ) const=0;

   /// compute and return the wheel torque
   virtual EcReal wheelTorque
      (
      ) const=0;
};

#endif // ecBaseRigidWheelSoilInteraction_H_
