#ifndef ecIncludeControlExpressions_H_
#define ecIncludeControlExpressions_H_
//------------------------------------------------------------------------------
// Copyright (c) 2004-2013 Energid Technologies. All rights reserved.
//
/// @file ecIncludeControlExpressions.h
/// @brief A convenient include file for all control expressions.
//
//------------------------------------------------------------------------------
#include "ecContExpAbCore.h"
#include "ecContExpCollisionAvoidanceAb.h"
#include "ecContExpColumnTableFunction.h"
#include "ecContExpCore.h"
#include "ecContExpEndErrorFilter.h"
#include "ecContExpEndErrorWeights.h"
#include "ecContExpEndMotionFilter.h"
#include "ecContExpErrorReduction.h"
#include "ecContExpErrorSensitivity.h"
#include "ecContExpGravTorqueGrad.h"
#include "ecContExpJointLimAvoid.h"
#include "ecContExpJointLimitFilter.h"
#include "ecContExpJointRateFilter.h"
#include "ecContExpJointValue.h"
#include "ecContExpMassMatrix.h"
#include "ecContExpMassMatrixAb.h"
#include "ecContExpMatrixToAb.h"
#include "ecContExpObstAvoid.h"
#include "ecContExpObstAvoidAb.h"
#include "ecContExpPotEnGradient.h"
#include "ecContExpPlanarTracksFilter.h"
#include "ecContExpSingAvoid.h"
#include "ecContExpStrOpt.h"
#include "ecContExpVectorToAb.h"
#include "ecExpAnd.h"
#include "ecExpBaseBinary.h"
#include "ecExpBaseUnary.h"
#include "ecExpContainer.h"
#include "ecExpCosine.h"
#include "ecExpDiagMatrix.h"
#include "ecExpElement.h"
#include "ecExpElementInverse.h"
#include "ecExpGE.h"
#include "ecExpGenColumn.h"
#include "ecExpGT.h"
#include "ecExpIdentityMatrix.h"
#include "ecExpLE.h"
#include "ecExpElementLog.h"
#include "ecExpElementLogN.h"
#include "ecExpLT.h"
#include "ecExpMinus.h"
#include "ecExpNegative.h"
#include "ecExpOr.h"
#include "ecExpPlus.h"
#include "ecExpElementPow.h"
#include "ecExpElementRoot.h"
#include "ecExpScalarConstant.h"
#include "ecExpSine.h"
#include "ecExpSingElCol.h"
#include "ecExpSingElMatrix.h"
#include "ecExpTimes.h"
#include "ecExpTranspose.h"

#endif // ecIncludeControlExpressions_H_
