#ifndef ecGraspingTokens_H_
#define ecGraspingTokens_H_
//------------------------------------------------------------------------------
// Copyright (c) 2004-2013 Energid Technologies. All rights reserved.
//
/// @file ecGraspingTokens.h
/// @brief Tokens for grasping project
/// @details namespace EcGrasping
//
//------------------------------------------------------------------------------
#include <actin/actin_config.h>
#include <xml/ecToken.h>

/// Tokens for grasping project
namespace EcGrasping
{
   ECTOKEN_DEFINITIONS(EC_ACTIN_GRASPING_DECL,
      // Namespace for this class.  Used in later definitions.
      (ns, "http://www.energid.com/namespace/ct#")

      // Elements
      (EcAbsoluteAngleFlagToken,                       ns + "absoluteAngleFlag")
      (EcActualOffsetToken,                            ns + "actualOffset")
      (EcActualPlacementGraspOffsetToken,              ns + "actualPlacementGraspOffset")
      (EcActualPlacementGraspOffsetStateToken,         ns + "actualPlacementGraspOffsetState")
      (EcAngleValuesToken,                             ns + "angleValues")
      (EcAverageDistanceDataToken,                     ns + "averageDistanceData")
      (EcBisectionGraspContactLocatorToken,            ns + "bisectionGraspContactLocator")
      (EcBreakPointToken,                              ns + "breakPoint")
      (EcBreakPointTesterToken,                        ns + "breakPointTester")
      (EcComparisonShapeFeatureHistogramToken,         ns + "comparisonShapeFeatureHistogram")
      (EcConstantGraspOffsetToken,                     ns + "constantGraspOffset")
      (EcConstantGraspOffsetStateToken,                ns + "constantGraspOffsetState")
      (EcConvergenceValueToken,                        ns + "convergenceValue")
      (EcConvergenceWindowToken,                       ns + "convergenceWindow")
      (EcConvergenceWindowStartTimeToken,              ns + "convergenceWindowStartTime")
      (EcCurrentFrameIndexToken,                       ns + "currentFrameIndex")
      (EcCurrentFrameIsCompleteToken,                  ns + "currentFrameIsComplete")
      (EcCurrentFrameNeedsInitToken,                   ns + "currentFrameNeedsInit")
      (EcCurrentSequenceIndexToken,                    ns + "currentSequenceIndex")
      (EcCurrentSequenceIsCompleteToken,               ns + "currentSequenceIsComplete")
      (EcCurrentSequenceNeedsInitToken,                ns + "currentSequenceNeedsInit")
      (EcCurrentSequenceStateToken,                    ns + "currentSequenceState")
      (EcDecisionTreeArticulatedModelBranchToken,      ns + "articulatedModelBranch")
      (EcDecisionTreeBoxBranchToken,                   ns + "boxBranch")
      (EcDecisionTreeCapsuleBranchToken,               ns + "capsuleBranch")
      (EcDecisionTreeConvexBranchToken,                ns + "convexBranch")
      (EcDecisionTreeFamilyBranchToken,                ns + "familyBranch")
      (EcDecisionTreePassThroughBranchToken,           ns + "passThroughBranch")
      (EcDecisionTreeShapeMatchingBranchToken,         ns + "shapeMatchingBranch")
      (EcDecisionTreeSphereBranchToken,                ns + "sphereBranch")
      (EcDissimilarityThresholdValueToken,             ns + "dissimilarityThresholdValue")
      (EcDistalFingerLinksToken,                       ns + "distalFingerLinks")
      (EcDistanceValuesToken,                          ns + "distanceValues")
      (EcEditorGraspFrameDataToken,                    ns + "editorGraspFrameData")
      (EcEditorGraspFrameDataVectorToken,              ns + "editorGraspFrameDataVector")
      (EcEditorGraspSequenceToken,                     ns + "editorGraspSequence")
      (EcFamilyToken,                                  ns + "family")
      (EcFeatureSetSizeToken,                          ns + "featureSetSize")
      (EcForceAchievedTransitionEventToken,            ns + "forceAchievedTransitionEvent")
      (EcForceAchievedTransitionEventStateToken,       ns + "forceAchievedTransitionEventState")
      (EcForceDetectedTransitionEventToken,            ns + "forceDetectedTransitionEvent")
      (EcForceDetectedTransitionEventStateToken,       ns + "forceDetectedTransitionEventState")
      (EcFrameIndexToken,                              ns + "frameIndex")
      (EcFrameRelativeGraspOffsetToken,                ns + "frameRelativeGraspOffset")
      (EcFrameRelativeGraspOffsetStateToken,           ns + "frameRelativeGraspOffsetState")
      (EcGraspActiveControlDescriptionToken,           ns + "graspActiveControlDescription")
      (EcGraspActiveForceControlDescriptionToken,      ns + "graspActiveForceControlDescription")
      (EcGraspCurrentEndEffectorPlacementToken,        ns + "graspCurrentEndEffectorPlacement")
      (EcGraspForceToken,                              ns + "graspForce")
      (EcGraspFrameContainerToken,                     ns + "graspFrameContainer")
      (EcGraspFrameContainerVectorToken,               ns + "graspFrameVector")
      (EcGraspFrameStateContainerToken,                ns + "graspFrameStateContainer")
      (EcGraspFrameStateContainerVectorToken,          ns + "graspFrameStateVector")
      (EcGraspFrameTransitionEventContainerToken,      ns + "graspFrameTransitionEventContainer")
      (EcGraspFrameTransitionEventToken,               ns + "graspFrameTransitionEvent")
      (EcGraspFrameTransitionEventStateContainerToken, ns + "graspFrameTransitionEventStateContainer")
      (EcGraspFrameTransitionEventStateToken,          ns + "graspFrameTransitionEventState")
      (EcGraspGoalEndEffectorPlacementToken,           ns + "graspGoalEndEffectorPlacement")
      (EcGraspingDecisionTreeContainerToken,           ns + "graspingDecisionTreeContainer")
      (EcGraspingDecisionTreeLeafToken,                ns + "graspingDecisionTreeLeaf")
      (EcGraspingDecisionTreeTestContainerToken,       ns + "graspingDecisionTreeTestContainer")
      (EcGraspingDecisionTreeToken,                    ns + "graspingDecisionTree")
      (EcGraspingFrameXAxisSourceFrame,                ns + "graspingFrameXAxisSourceFrame")
      (EcGraspingFrameXAxisVector,                     ns + "graspingFrameXAxisVector")
      (EcGraspingFrameYAxisSourceFrame,                ns + "graspingFrameYAxisSourceFrame")
      (EcGraspingFrameYAxisVector,                     ns + "graspingFrameYAxisVector")
      (EcGraspingFrameZAxisSourceFrame,                ns + "graspingFrameZAxisSourceFrame")
      (EcGraspingFrameZAxisVector,                     ns + "graspingFrameZAxisVector")
      (EcGraspOffsetContainerToken,                    ns + "graspOffsetContainer")
      (EcGraspOffsetContainerVectorToken,              ns + "graspOffsetContainerVector")
      (EcGraspOffsetStateContainerToken,               ns + "graspOffsetStateContainer")
      (EcGraspOffsetStateContainerVectorToken,         ns + "graspOffsetStateContainerVector")
      (EcGraspOffsetToken,                             ns + "graspOffset")
      (EcGraspOffsetStateToken,                        ns + "graspOffsetState")
      (EcGraspQualityMeasureToken,                     ns + "graspQualityMeasure")
      (EcGraspSequenceToken,                           ns + "graspSequence")
      (EcGraspSequenceStateToken,                      ns + "graspSequenceState")
      (EcGraspSequenceManagerToken,                    ns + "graspSequenceManager")
      (EcGraspSequenceManagerStateToken,               ns + "graspSequenceManagerState")
      (EcGraspSequenceMapToken,                        ns + "graspSequenceMap")
      (EcHandDescriptorToken,                          ns + "handDescription")
      (EcHandGraspingModuleToken,                      ns + "handGraspingModule")
      (EcHistogramDataToken,                           ns + "histogramData")
      (EcIncrementalGraspContactLocatorToken,          ns + "incrementalGraspContactLocator")
      (EcIndexToken,                                   ns + "index")
      (EcInitializationTimeToken,                      ns + "initializationTime")
      (EcInterpolationTimeToken,                       ns + "interpolationTime")
      (EcInterpolatedCurrentOffsetToken,               ns + "interpolatedCurrentOffset")
      (EcInterpolatedGraspOffsetToken,                 ns + "interpolatedGraspOffset")
      (EcInterpolatedGraspOffsetStateToken,            ns + "interpolatedGraspOffsetState")
      (EcInterpolatedInitialOffsetToken,               ns + "interpolatedInitialOffset")
      (EcIsNormalizedToken,                            ns + "isNormalized")
      (EcJointPositionRangesToken,                     ns + "jointPositionRanges")
      (EcLeftBranchToken,                              ns + "leftBranch")
      (EcLinkFrameTypeToken,                           ns + "linkFrameType")
      (EcLinkIdentifiersToken,                         ns + "linkIdentifiers")
      (EcLinkLabelsToken,                              ns + "linkLabels")
      (EcLinkRelativeGraspOffsetToken,                 ns + "linkRelativeGraspOffset")
      (EcLinkRelativeGraspOffsetStateToken,            ns + "linkRelativeGraspOffsetState")
      (EcManipulatorGraspingModuleToken,               ns + "manipulatorGraspingModule")
      (EcMaxValueToken,                                ns + "maxValue")
      (EcNumAngleBinsToken,                            ns + "numAngleBins")
      (EcNumDistanceBinsToken,                         ns + "numDistanceBins")
      (EcNumPointsToken,                               ns + "numPoints")
      (EcObjectGraspingModuleToken,                    ns + "objectGraspingModule")
      (EcObjectRelativeGraspOffsetToken,               ns + "objectRelativeGraspOffset")
      (EcObjectRelativeGraspOffsetStateToken,          ns + "objectRelativeGraspOffsetState")
      (EcParametricCurrentOffsetToken,                 ns + "parametricCurrentOffset")
      (EcParametricGraspFrameToken,                    ns + "parametricGraspFrame")
      (EcParametricGraspFrameStateToken,               ns + "parametricGraspFrameState")
      (EcParametricIndexToken,                         ns + "parametricIndex")
      (EcParametricTagToken,                           ns + "parametricTag")
      (EcParametricTransformToken,                     ns + "parametricTransform")
      (EcParametricTranslationGraspOffsetToken,        ns + "parametricTranslationGraspOffset")
      (EcParametricTranslationGraspOffsetStateToken,   ns + "parametricTranslationGraspOffsetState")
      (EcParametricValuesToken,                        ns + "parametricValues")
      (EcParametricXTagToken,                          ns + "parametricXTag")
      (EcParametricYTagToken,                          ns + "parametricYTag")
      (EcParametricZTagToken,                          ns + "parametricZTag")
      (EcPlacementConvergenceValueToken,               ns + "placementConvergenceValue")
      (EcPlacementConvergenceWindowToken,              ns + "placementConvergenceWindow")
      (EcPlacementConvergenceWindowStartTimeToken,     ns + "placementConvergenceWindowStartTime")
      (EcPlacementTestIndicesToken,                    ns + "placementTestIndices")
      (EcPlacementToleranceToken,                      ns + "placementTolerance")
      (EcPlacementAchievedTransitionEventToken,        ns + "placementAchievedTransitionEvent")
      (EcPlacementAchievedTransitionEventStateToken,   ns + "placementAchievedTransitionEventState")
      (EcRelativeCurrentOffsetToken,                   ns + "relativeCurrentOffset")
      (EcRelativeOffsetToken,                          ns + "relativeOffset")
      (EcRelativeOffsetStateToken,                     ns + "relativeOffsetState")
      (EcRightBranchToken,                             ns + "rightBranch")
      (EcScaleToken,                                   ns + "scale")
      (EcSequenceMapToken,                             ns + "sequenceMap")
      (EcSequenceOrderToken,                           ns + "sequenceOrder")
      (EcShapeFeatureHistogramToken,                   ns + "shapeFeatureHistogram")
      (EcShapeFeatureNormalizedHistogramToken,         ns + "shapeFeatureNormalizedHistogram")
      (EcShapeFeatureSetToken,                         ns + "shapeFeatureSet")
      (EcShapeMatchingAlgorithmToken,                  ns + "shapeMatchingAlgorithm")
      (EcSoftFailureToken,                             ns + "softFailure")
      (EcStepSizeToken,                                ns + "stepSize")
      (EcSizeToken,                                    ns + "size")
      (EcStageIBarbellGraspingRhToken,                 ns + "stageIBarbellGraspingRh")
      (EcStageIBoxGraspingRhToken,                     ns + "stageIBoxGraspingRh")
      (EcStageICapsuleGraspingRhToken,                 ns + "stageICapsuleGraspingRh")
      (EcStageIGraspingContainerToken,                 ns + "stageIGraspingContainer")
      (EcStageISequenceGraspingToken,                  ns + "stageISequenceGrasping")
      (EcStageISphereGraspingRhToken,                  ns + "stageISphereGraspingRh")
      (EcStageINewSphereGraspingRhToken,               ns + "stageINewSphereGraspingRh")
      (EcStageIIGraspingContainerToken,                ns + "stageIIGraspingContainer")
      (EcStageIIGraspingPassThroughToken,              ns + "stageIIGraspingPassThrough")
      (EcStageIIIGraspingContainerToken,               ns + "stageIIIGraspingContainer")
      (EcStageIIIGraspingPassThroughToken,             ns + "stageIIIGraspingPassThrough")
      (EcStandardGraspFrameToken,                      ns + "standardGraspFrame")
      (EcStandardGraspFrameStateToken,                 ns + "standardGraspFrameState")
      (EcSubsequenceGraspFrameToken,                   ns + "subsequenceGraspFrame")
      (EcSubsequenceGraspFrameStateToken,              ns + "subsequenceGraspFrameState")
      (EcTagToken,                                     ns + "tag")
      (EcTargetFrameToken,                             ns + "targetFrame")
      (EcTargetFrameStateToken,                        ns + "targetFrameState")
      (EcTargetOffsetToken,                            ns + "targetOffset")
      (EcTargetOffsetStateToken,                       ns + "targetOffsetState")
      (EcTestIndicesToken,                             ns + "testIndices")
      (EcTimeDurationToken,                            ns + "timeDuration")
      (EcTimeDurationTransitionEventToken,             ns + "timeDurationTransitionEvent")
      (EcTimeDurationTransitionEventStateToken,        ns + "timeDurationTransitionEventState")
      (EcTimeoutPeriodToken,                           ns + "timeoutPeriod")
      (EcTimeoutStartTimeToken,                        ns + "timeoutStartTime")
      (EcToleranceToken,                               ns + "tolerance")
      (EcTriggerTimeToken,                             ns + "triggerTime")
      (EcUseIndexToken,                                ns + "useIndex")

      // Enumerations ... don't need namespace
      (EcDhFrameToken,                                 "dhFrame")
      (EcObjectFrameToken,                             "objectFrame")
      (EcPrimaryFrameToken,                            "primaryFrame")
      (EcSystemFrameToken,                             "systemFrame")
      (EcUndefinedFrameToken,                          "undefinedFrame")
   )
}

#endif // ecGraspingTokens_H_
